### ISSUE TITLE
Add a second fire button

### ISSUE THREAD

**Issue by danko79** [Retro-Commodore/RCEU505-Simple-joystick-tester#1]
Hi,you can make a new rev of this with test a second fire button?

**Comment by tomse** [comment]
yes, there is a newer model on it's way. though I still need to receive the components before I release the new version.

**Comment by danko79** [comment]
Thanks!

**Comment by tomse** [comment]
Sorry, I totally forgot about this one. I saw you closing it today, 
I've made some changes and release a new revision.

The other I'm doing is yet to be released.
